### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by visonpon** [Kebii/R2ET#4]
Hi @Kebii , thanks for sharing this wonderful work, but using` inference_bvh.py`,I got the size mismatch error when load the pretrain shape_aware model, hope you can check , thanks~

**Comment by Kebii** [comment]
Thanks for pointing out this problem. I have fixed it, and some other bugs, in the latest code.
This size mismatch error is due to the fact that the pre-training weights of the Shape-aware Module I provided involve the input of the source character's shape information, which is slightly different from the model introduced in the paper. Still, it does not affect the final result. In fact, the Shape-aware Module only requires the target character's shape information to perceive geometry, as introduced in the paper.
